### ISSUE TITLE
Авторов необходимо сделать в другой таблице, что бы было отношение много (авторов) к одному (книге)

### ISSUE THREAD

**Issue by tupichkindenis** [progressicu/library#3]
https://github.com/progressicu/library/blob/2109fc9f2ae9f61f86e96cf931b5fb0b55afaccf/src/main/java/library/model/Book.java#L13

**Comment by progressicu** [comment]
Сделал отношение. Но теперь поиск не работает. Работает только по одному критерию. Пытаюсь исправить

**Comment by progressicu** [comment]
Исправил поиск, но не думаю, что так правильно. 
Попытаюсь, что-нибудь другое придумать в скором времени
